/**
 * petplay:pet:v1 — the pet's identity and look.
 *
 * A pet is either a PARTS sprite (species + ears / eyes / body / tail /
 * accessory + three colours, all drawn as SVG in <PetSprite>) or a PHOTO
 * sprite (a data: URL produced by cropping and tinting a local image on a
 * canvas in this browser). Every part and colour is free. Nothing here is a
 * catalog with a price, a token or a lock, and nothing is generated by an AI
 * model: the art is a fixed set of SVG shapes.
 */

export const PET_KEY = "petplay:pet:v1";

export const SPECIES = ["dog", "cat", "bunny", "bird", "fox"] as const;
export type Species = (typeof SPECIES)[number];

export const EARS = ["round", "pointy", "floppy", "long", "tuft"] as const;
export const EYES = ["dot", "round", "happy", "sleepy", "star"] as const;
export const BODIES = ["round", "tall", "chunky"] as const;
export const TAILS = ["curl", "straight", "fluffy", "short"] as const;
export const ACCESSORIES = ["none", "bow", "collar", "scarf", "hat"] as const;

export type Ears = (typeof EARS)[number];
export type Eyes = (typeof EYES)[number];
export type Body = (typeof BODIES)[number];
export type Tail = (typeof TAILS)[number];
export type Accessory = (typeof ACCESSORIES)[number];

export interface Parts {
  ears: Ears;
  eyes: Eyes;
  body: Body;
  tail: Tail;
  accessory: Accessory;
}

export interface Colors {
  primary: string;
  secondary: string;
  accent: string;
}

export interface PhotoSprite {
  /** Always a data:image/... URL rendered on this device. Never a remote URL. */
  dataUrl: string;
  tint?: string;
}

export interface Pet {
  id: string;
  name: string;
  species: Species;
  parts: Parts;
  colors: Colors;
  photoSprite?: PhotoSprite;
  createdAt: string;
  updatedAt: string;
}

/** Fixed palette of swatches. The colour input accepts anything else too. */
export const PALETTE: { primary: string[]; secondary: string[]; accent: string[] } = {
  primary: ["#f6c9a0", "#c9a27a", "#8b5e3c", "#4a4a4a", "#f2f2f2", "#f4a261", "#9bb7d4", "#c8a2c8", "#a3c9a8", "#f7b2c4"],
  secondary: ["#fff5f0", "#ffe8d6", "#f8d9c0", "#ffffff", "#e8e1d9", "#ffd6e0", "#d6f5ef", "#fce7a4", "#e9d5ff", "#cfe6ff"],
  accent: ["#fb7185", "#2dd4bf", "#f59e0b", "#60a5fa", "#a78bfa", "#34d399", "#f97316", "#ec4899", "#14b8a6", "#1f2937"],
};

/** Species defaults so a fresh pick already looks right. */
export const SPECIES_DEFAULTS: Record<Species, { parts: Parts; colors: Colors }> = {
  dog: { parts: { ears: "floppy", eyes: "round", body: "chunky", tail: "curl", accessory: "collar" }, colors: { primary: "#c9a27a", secondary: "#fff5f0", accent: "#fb7185" } },
  cat: { parts: { ears: "pointy", eyes: "happy", body: "round", tail: "straight", accessory: "bow" }, colors: { primary: "#4a4a4a", secondary: "#f2f2f2", accent: "#2dd4bf" } },
  bunny: { parts: { ears: "long", eyes: "dot", body: "round", tail: "short", accessory: "none" }, colors: { primary: "#f2f2f2", secondary: "#ffd6e0", accent: "#fb7185" } },
  bird: { parts: { ears: "tuft", eyes: "round", body: "tall", tail: "fluffy", accessory: "scarf" }, colors: { primary: "#f4a261", secondary: "#fce7a4", accent: "#2dd4bf" } },
  fox: { parts: { ears: "pointy", eyes: "happy", body: "tall", tail: "fluffy", accessory: "none" }, colors: { primary: "#f97316", secondary: "#fff5f0", accent: "#1f2937" } },
};

export function isSpecies(v: unknown): v is Species {
  return typeof v === "string" && (SPECIES as readonly string[]).includes(v);
}

function pick<T extends string>(list: readonly T[], v: unknown, fallback: T): T {
  return typeof v === "string" && (list as readonly string[]).includes(v) ? (v as T) : fallback;
}

/** #rgb or #rrggbb only, so a backup can never inject a url() or a script. */
export function isHexColor(v: unknown): v is string {
  return typeof v === "string" && /^#(?:[0-9a-f]{3}|[0-9a-f]{6})$/i.test(v);
}

export function normalizeColor(v: unknown, fallback: string): string {
  return isHexColor(v) ? v.toLowerCase() : fallback;
}

/**
 * A photo sprite is only accepted as an inline data:image/ URL. http(s):,
 * blob:, or anything remote is dropped: the picture must live in the backup
 * itself, never behind a network fetch.
 */
export function isLocalImageDataUrl(v: unknown): v is string {
  return typeof v === "string" && /^data:image\/(?:png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(v) && v.length < 4_000_000;
}

export function newId(): string {
  return `${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`;
}

export const NAME_MAX = 24;

export function cleanName(v: unknown, fallback: string): string {
  const s = typeof v === "string" ? v.replace(/\s+/g, " ").trim().slice(0, NAME_MAX) : "";
  return s || fallback;
}

export function newPet(name: string, species: Species = "cat", now: Date = new Date()): Pet {
  const d = SPECIES_DEFAULTS[species];
  const iso = now.toISOString();
  return {
    id: newId(),
    name: cleanName(name, "Mochi"),
    species,
    parts: { ...d.parts },
    colors: { ...d.colors },
    createdAt: iso,
    updatedAt: iso,
  };
}

/** Coerces anything (storage, a backup, a hand-edited file) into a valid pet. */
export function normalizePet(raw: unknown, fallbackName = "Mochi"): Pet | null {
  if (!raw || typeof raw !== "object") return null;
  const o = raw as Record<string, unknown>;
  const species = isSpecies(o.species) ? o.species : "cat";
  const d = SPECIES_DEFAULTS[species];
  const p = (o.parts && typeof o.parts === "object" ? o.parts : {}) as Record<string, unknown>;
  const c = (o.colors && typeof o.colors === "object" ? o.colors : {}) as Record<string, unknown>;
  const iso = new Date().toISOString();
  const pet: Pet = {
    id: typeof o.id === "string" && o.id ? o.id : newId(),
    name: cleanName(o.name, fallbackName),
    species,
    parts: {
      ears: pick(EARS, p.ears, d.parts.ears),
      eyes: pick(EYES, p.eyes, d.parts.eyes),
      body: pick(BODIES, p.body, d.parts.body),
      tail: pick(TAILS, p.tail, d.parts.tail),
      accessory: pick(ACCESSORIES, p.accessory, d.parts.accessory),
    },
    colors: {
      primary: normalizeColor(c.primary, d.colors.primary),
      secondary: normalizeColor(c.secondary, d.colors.secondary),
      accent: normalizeColor(c.accent, d.colors.accent),
    },
    createdAt: typeof o.createdAt === "string" ? o.createdAt : iso,
    updatedAt: typeof o.updatedAt === "string" ? o.updatedAt : iso,
  };
  const ps = o.photoSprite as Record<string, unknown> | undefined;
  if (ps && typeof ps === "object" && isLocalImageDataUrl(ps.dataUrl)) {
    pet.photoSprite = { dataUrl: ps.dataUrl, ...(isHexColor(ps.tint) ? { tint: ps.tint.toLowerCase() } : {}) };
  }
  return pet;
}

export function touchPet(pet: Pet, now: Date = new Date()): Pet {
  return { ...pet, updatedAt: now.toISOString() };
}

/** Switching species resets parts and colours to that species' defaults. */
export function withSpecies(pet: Pet, species: Species): Pet {
  const d = SPECIES_DEFAULTS[species];
  return touchPet({ ...pet, species, parts: { ...d.parts }, colors: { ...d.colors } });
}

export function withPart<K extends keyof Parts>(pet: Pet, key: K, value: Parts[K]): Pet {
  return touchPet({ ...pet, parts: { ...pet.parts, [key]: value } });
}

export function withColor(pet: Pet, key: keyof Colors, value: string): Pet {
  return touchPet({ ...pet, colors: { ...pet.colors, [key]: normalizeColor(value, pet.colors[key]) } });
}

export function withPhotoSprite(pet: Pet, sprite: PhotoSprite | null): Pet {
  if (!sprite) {
    const { photoSprite: _drop, ...rest } = pet;
    void _drop;
    return touchPet(rest);
  }
  if (!isLocalImageDataUrl(sprite.dataUrl)) return pet;
  return touchPet({ ...pet, photoSprite: { dataUrl: sprite.dataUrl, ...(isHexColor(sprite.tint) ? { tint: sprite.tint } : {}) } });
}

/** Random parts + palette colours for the current species. Free, like everything else. */
export function randomLook(pet: Pet, rnd: () => number = Math.random): Pet {
  const at = <T,>(list: readonly T[]): T => list[Math.floor(rnd() * list.length)] ?? list[0];
  return touchPet({
    ...pet,
    parts: { ears: at(EARS), eyes: at(EYES), body: at(BODIES), tail: at(TAILS), accessory: at(ACCESSORIES) },
    colors: { primary: at(PALETTE.primary), secondary: at(PALETTE.secondary), accent: at(PALETTE.accent) },
  });
}

export function loadPet(fallbackName = "Mochi"): Pet | null {
  try {
    const raw = localStorage.getItem(PET_KEY);
    return raw ? normalizePet(JSON.parse(raw), fallbackName) : null;
  } catch {
    return null;
  }
}

export function savePet(pet: Pet): void {
  try {
    localStorage.setItem(PET_KEY, JSON.stringify(pet));
  } catch {
    /* private mode or quota: the session still works, it just will not persist */
  }
}

export function clearPet(): void {
  try {
    localStorage.removeItem(PET_KEY);
  } catch {
    /* ignore */
  }
}
