// Generated by scripts/generate-puzzles.ts. Do not edit manually.
import type { PuzzleDefinition } from './puzzle-definition';

export type { PuzzleDefinition } from './puzzle-definition';

export const PUZZLES: readonly PuzzleDefinition[] = Object.freeze(
  [
    {
      "id": "beginner-1",
      "puzzle": "312978546978645213645312879291867435034291768867534192756423981423189657189756324",
      "solution": "312978546978645213645312879291867435534291768867534192756423981423189657189756324",
      "difficulty": "beginner",
      "analysis": {
        "singles": 1,
        "hiddenSingles": 0,
        "lockedEliminations": 0,
        "pairEliminations": 0,
        "searchNodes": 0,
        "maxSearchDepth": 0,
        "difficulty": "beginner"
      }
    },
    {
      "id": "beginner-2",
      "puzzle": "312978540978645213645312879291867435034291768867534192756423981423189657189756324",
      "solution": "312978546978645213645312879291867435534291768867534192756423981423189657189756324",
      "difficulty": "beginner",
      "analysis": {
        "singles": 2,
        "hiddenSingles": 0,
        "lockedEliminations": 0,
        "pairEliminations": 0,
        "searchNodes": 0,
        "maxSearchDepth": 0,
        "difficulty": "beginner"
      }
    },
    {
      "id": "beginner-3",
      "puzzle": "312978540978645213645312879291867405034291768867534192756423981423189657189756324",
      "solution": "312978546978645213645312879291867435534291768867534192756423981423189657189756324",
      "difficulty": "beginner",
      "analysis": {
        "singles": 3,
        "hiddenSingles": 0,
        "lockedEliminations": 0,
        "pairEliminations": 0,
        "searchNodes": 0,
        "maxSearchDepth": 0,
        "difficulty": "beginner"
      }
    },
    {
      "id": "easy-1",
      "puzzle": "302978540978645013645312879291867405004291760067530192756423901423180657189756324",
      "solution": "312978546978645213645312879291867435534291768867534192756423981423189657189756324",
      "difficulty": "easy",
      "analysis": {
        "singles": 10,
        "hiddenSingles": 1,
        "lockedEliminations": 0,
        "pairEliminations": 0,
        "searchNodes": 0,
        "maxSearchDepth": 0,
        "difficulty": "easy"
      }
    },
    {
      "id": "easy-2",
      "puzzle": "302978540978645010645312879291867405004291760067530192756423901423180657189756324",
      "solution": "312978546978645213645312879291867435534291768867534192756423981423189657189756324",
      "difficulty": "easy",
      "analysis": {
        "singles": 11,
        "hiddenSingles": 1,
        "lockedEliminations": 0,
        "pairEliminations": 0,
        "searchNodes": 0,
        "maxSearchDepth": 0,
        "difficulty": "easy"
      }
    },
    {
      "id": "easy-3",
      "puzzle": "302978540978645010645312879291867405004291760067030192756423901423180657189756324",
      "solution": "312978546978645213645312879291867435534291768867534192756423981423189657189756324",
      "difficulty": "easy",
      "analysis": {
        "singles": 11,
        "hiddenSingles": 2,
        "lockedEliminations": 0,
        "pairEliminations": 0,
        "searchNodes": 0,
        "maxSearchDepth": 0,
        "difficulty": "easy"
      }
    },
    {
      "id": "medium-1",
      "puzzle": "302070540078040000000002009291867000000001700000000192750023901003000000000750300",
      "solution": "312978546978645213645312879291867435534291768867534192756423981423189657189756324",
      "difficulty": "medium",
      "analysis": {
        "singles": 12,
        "hiddenSingles": 38,
        "lockedEliminations": 6,
        "pairEliminations": 0,
        "searchNodes": 0,
        "maxSearchDepth": 0,
        "difficulty": "medium"
      }
    },
    {
      "id": "medium-2",
      "puzzle": "302070540078040000000002009291867000000000700000000192750023901003000000000750300",
      "solution": "312978546978645213645312879291867435534291768867534192756423981423189657189756324",
      "difficulty": "medium",
      "analysis": {
        "singles": 12,
        "hiddenSingles": 39,
        "lockedEliminations": 1,
        "pairEliminations": 7,
        "searchNodes": 0,
        "maxSearchDepth": 0,
        "difficulty": "medium"
      }
    },
    {
      "id": "medium-3",
      "puzzle": "302070540078040000000002009291867000000000700000000192750023901003000000000750000",
      "solution": "312978546978645213645312879291867435534291768867534192756423981423189657189756324",
      "difficulty": "medium",
      "analysis": {
        "singles": 11,
        "hiddenSingles": 41,
        "lockedEliminations": 6,
        "pairEliminations": 5,
        "searchNodes": 0,
        "maxSearchDepth": 0,
        "difficulty": "medium"
      }
    },
    {
      "id": "hard-1",
      "puzzle": "010570204006003001200009000354901600000600005080000010005000700090005000030708456",
      "solution": "819576234576243891243819567354921678921687345687354912465132789798465123132798456",
      "difficulty": "hard",
      "analysis": {
        "singles": 8,
        "hiddenSingles": 22,
        "lockedEliminations": 9,
        "pairEliminations": 0,
        "searchNodes": 2,
        "maxSearchDepth": 1,
        "difficulty": "hard"
      }
    },
    {
      "id": "hard-2",
      "puzzle": "000570204006003001200009000354901600000600005080000010005000700090005000030708456",
      "solution": "819576234576243891243819567354921678921687345687354912465132789798465123132798456",
      "difficulty": "hard",
      "analysis": {
        "singles": 9,
        "hiddenSingles": 22,
        "lockedEliminations": 9,
        "pairEliminations": 0,
        "searchNodes": 2,
        "maxSearchDepth": 1,
        "difficulty": "hard"
      }
    },
    {
      "id": "hard-3",
      "puzzle": "000570204006003001200009000304901600000600005080000010005000700090005000030708456",
      "solution": "819576234576243891243819567354921678921687345687354912465132789798465123132798456",
      "difficulty": "hard",
      "analysis": {
        "singles": 9,
        "hiddenSingles": 23,
        "lockedEliminations": 9,
        "pairEliminations": 0,
        "searchNodes": 2,
        "maxSearchDepth": 1,
        "difficulty": "hard"
      }
    },
    {
      "id": "expert-1",
      "puzzle": "030000000800002040001045006000400900000000320078103000080000060403007100000090402",
      "solution": "534678219867912543291345876312456987645789321978123654189234765423567198756891432",
      "difficulty": "expert",
      "analysis": {
        "singles": 3,
        "hiddenSingles": 6,
        "lockedEliminations": 6,
        "pairEliminations": 3,
        "searchNodes": 4,
        "maxSearchDepth": 4,
        "difficulty": "expert"
      }
    },
    {
      "id": "expert-2",
      "puzzle": "000570204006003001200009000304901000000600005080000010005000700090005000030708456",
      "solution": "819576234576243891243819567354921678921687345687354912465132789798465123132798456",
      "difficulty": "expert",
      "analysis": {
        "singles": 13,
        "hiddenSingles": 11,
        "lockedEliminations": 7,
        "pairEliminations": 2,
        "searchNodes": 4,
        "maxSearchDepth": 2,
        "difficulty": "expert"
      }
    },
    {
      "id": "expert-3",
      "puzzle": "000570204006003001200009000304901000000600005080000010005000700090000000030708456",
      "solution": "819576234576243891243819567354921678921687345687354912465132789798465123132798456",
      "difficulty": "expert",
      "analysis": {
        "singles": 15,
        "hiddenSingles": 10,
        "lockedEliminations": 7,
        "pairEliminations": 2,
        "searchNodes": 4,
        "maxSearchDepth": 2,
        "difficulty": "expert"
      }
    }
  ],
);
